"""revised to user relation

Revision ID: 119ae06c1acb
Revises: 687e2752aaf0
Create Date: 2025-09-26 14:38:54.143809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '119ae06c1acb'
down_revision = '687e2752aaf0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
