"""更改training表

Revision ID: 1ba1f16e633d
Revises: c93aa37f1779
Create Date: 2025-05-25 18:58:16.736855

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1ba1f16e633d'
down_revision = 'c93aa37f1779'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training', sa.Column('technical_title', sa.String(length=100), nullable=True))
    op.add_column('training', sa.Column('technical_items', mysql.LONGTEXT(), nullable=True))
    op.add_column('training', sa.Column('technical_feedback', sa.Text(), nullable=True))
    op.add_column('training', sa.Column('technical_completed', sa.Boolean(), nullable=True))
    op.add_column('training', sa.Column('coach_assigned_physical', sa.Text(), nullable=True))
    op.add_column('training', sa.Column('coach_assigned_technical', mysql.LONGTEXT(), nullable=True))
    op.add_column('training', sa.Column('coach_physical_done', sa.Boolean(), nullable=True))
    op.add_column('training', sa.Column('coach_technical_done', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('training', 'coach_technical_done')
    op.drop_column('training', 'coach_physical_done')
    op.drop_column('training', 'coach_assigned_technical')
    op.drop_column('training', 'coach_assigned_physical')
    op.drop_column('training', 'technical_completed')
    op.drop_column('training', 'technical_feedback')
    op.drop_column('training', 'technical_items')
    op.drop_column('training', 'technical_title')
    # ### end Alembic commands ###
