"""create tasks table

Revision ID: 3401c0c4bd1f
Revises: 8aeeebd3a5ea
Create Date: 2025-09-25 22:57:01.150740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3401c0c4bd1f'
down_revision = '8aeeebd3a5ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
