"""Add announcement model

Revision ID: 37a94b9cf652
Revises: 5def54358b5f
Create Date: 2025-04-25 16:30:51.725450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37a94b9cf652'
down_revision = '5def54358b5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
