"""create tasks table

Revision ID: 5c117367ee22
Revises: 3401c0c4bd1f
Create Date: 2025-09-25 23:03:24.711727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c117367ee22'
down_revision = '3401c0c4bd1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
