"""add bio and profile_pic to user

Revision ID: 5c30f293e960
Revises: d86936dd581b
Create Date: 2025-05-08 14:03:57.410594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c30f293e960'
down_revision = 'd86936dd581b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('bio', sa.String(500), nullable=True))
    op.add_column('user', sa.Column('profile_pic', sa.String(255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'profile_pic')
    op.drop_column('user', 'bio')
    # ### end Alembic commands ###
