"""revised to tasks

Revision ID: 687e2752aaf0
Revises: 8b93e32464d4
Create Date: 2025-09-26 14:32:33.745517

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '687e2752aaf0'
down_revision = '8b93e32464d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_training_tasks_id', table_name='training_tasks')
    op.drop_table('training_tasks')
    op.drop_index('ix_tasks_id', table_name='tasks')
    op.drop_table('tasks')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('category', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('item', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('description', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('completed', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('athlete_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('completed_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['athlete_id'], ['user.id'], name='tasks_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_tasks_id', 'tasks', ['id'], unique=False)
    op.create_table('training_tasks',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('category', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('item', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('description', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('completed', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='training_tasks_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_training_tasks_id', 'training_tasks', ['id'], unique=False)
    # ### end Alembic commands ###
