"""initial migration

Revision ID: 88c9d5b40888
Revises: 
Create Date: 2025-08-25 15:32:57.142677

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '88c9d5b40888'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index('user_id', table_name='coach_profiles')  # 已註解掉，避免外鍵衝突
    op.add_column('user', sa.Column('line_user_id', sa.String(length=128), nullable=True))
    op.create_unique_constraint(None, 'user', ['line_user_id'])
    # ### end Alembic commands ###



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'line_user_id')
    op.create_table('coach_profiles',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('full_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('phone', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('specialty', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('experience', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('bio', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('profile_pic', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='coach_profiles_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('user_id', 'coach_profiles', ['user_id'], unique=True)
    # ### end Alembic commands ###
