"""Add profile fields to user

Revision ID: c93aa37f1779
Revises: 5c30f293e960
Create Date: 2025-05-22 23:05:36.416113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c93aa37f1779'
down_revision = '5c30f293e960'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('full_name', sa.String(length=100), nullable=True))
    op.add_column('user', sa.Column('birth_date', sa.Date(), nullable=True))
    op.add_column('user', sa.Column('gender', sa.String(length=10), nullable=True))
    op.add_column('user', sa.Column('height', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('weight', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('region', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'region')
    op.drop_column('user', 'weight')
    op.drop_column('user', 'height')
    op.drop_column('user', 'gender')
    op.drop_column('user', 'birth_date')
    op.drop_column('user', 'full_name')
    # ### end Alembic commands ###
