"""add food_photos table

Revision ID: d9887e1a8c94
Revises: fe4406d51029
Create Date: 2025-08-12 11:55:32.144931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9887e1a8c94'
down_revision = 'fe4406d51029'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
