"""Add user_id to training_tasks

Revision ID: fd7658e7aa1f
Revises: 88c9d5b40888
Create Date: 2025-09-25 16:01:45.484220

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fd7658e7aa1f'
down_revision = '88c9d5b40888'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('user_id', table_name='coach_profiles')
    op.drop_table('coach_profiles')
    op.drop_table('training')
    op.alter_column('evaluation', 'training_status',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('evaluation', 'fitness',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('evaluation', 'sleep',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('evaluation', 'appetite',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.Integer(),
               existing_nullable=True)
    op.add_column('food_photos', sa.Column('athlete_username', sa.String(length=80), nullable=False))
    op.add_column('training_tasks', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'training_tasks', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'training_tasks', type_='foreignkey')
    op.drop_column('training_tasks', 'user_id')
    op.drop_column('food_photos', 'athlete_username')
    op.alter_column('evaluation', 'appetite',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=True)
    op.alter_column('evaluation', 'sleep',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=True)
    op.alter_column('evaluation', 'fitness',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=True)
    op.alter_column('evaluation', 'training_status',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=True)
    op.create_table('training',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('jump_type', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('jump_count', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('run_distance', mysql.FLOAT(), nullable=True),
    sa.Column('run_time', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('weight_part', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('weight_sets', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('agility_type', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('agility_note', mysql.TEXT(), nullable=True),
    sa.Column('special_focus', mysql.TEXT(), nullable=True),
    sa.Column('technical_title', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('technical_items', mysql.LONGTEXT(), nullable=True),
    sa.Column('technical_feedback', mysql.TEXT(), nullable=True),
    sa.Column('technical_completed', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('coach_assigned_physical', mysql.TEXT(), nullable=True),
    sa.Column('coach_assigned_technical', mysql.LONGTEXT(), nullable=True),
    sa.Column('coach_physical_done', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('coach_technical_done', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='training_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('coach_profiles',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('full_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('phone', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('specialty', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('experience', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('bio', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('profile_pic', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='coach_profiles_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('user_id', 'coach_profiles', ['user_id'], unique=True)
    # ### end Alembic commands ###
